- hosts: localhost 
  tasks:
  - name: trigger all the credentials 
    uri: 
      url: https://{{aap_hostname}}/api/v2/credentials/ 
      user: "{{aap_username}}"
      password: "{{aap_password}}"
      method: GET
      force_basic_auth: true 
      validate_certs: false 
    register: all_credentials
  - name: Show all credentials 
    debug: 
      var: all_credentials
  - name: Get all the IDs 
    debug:
      var: all_credentials.json.results | map(attribute="id") | list  
  - name: Copy awx-manage shell_plus commands to a script 
    copy:
      src: python-script.py
      dest: /tmp/python-script.py
  - name: Get Credentials output 
    shell: "awx-manage  shell_plus --quiet-load --plain  -c 'exec(open(\"/tmp/python-script.py\").read())'"
    environment:
      CRED_ID: "{{item}}"
    loop: "{{all_credentials.json.results | map(attribute='id') | list}}"
    register: all_creds_data
    failed_when: false 
  - name: Get all credentials sensitive data
    debug: 
      var: all_creds_data.results | map(attribute='stdout_lines') | list 
  - name: All creds with cred id 
    template:
      dest: /tmp/all_creds_file
      src: all_creds_file.j2
