- hosts: localhost 
  gather_facts: no
  vars:
    test: "hello"
  tasks:
  - name: trigger all the credentials 
    uri: 
      url: https://{{aap_hostname}}/api/v2/credentials/ 
      user: "{{aap_username}}"
      password: "{{aap_password}}"
      method: GET
      force_basic_auth: true 
      validate_certs: false 
    register: all_credentials
  - name: Show all credentials 
    debug: 
      var: all_credentials
  - name: Get all the IDs 
    debug:
      var: all_credentials.json.results | map(attribute="id") | list  
  - name: Copy awx-manage shell_plus commands to a script 
    copy:
      src: python-script.py
      dest: /tmp/python-script.py
  - name: Initialize a new dict for the cleared credentials 
    set_fact:
      credentials_unprotected: {}
  - name: show up credential for every cred detected
    include_tasks: retrieve_creds_values.yml
    vars:
      mycred: "{{item}}"
    loop: "{{all_credentials.json.results | map(attribute='id') | list}}"

  - name: Initialize a new dict for the cleared credentials 
    set_fact:
      controller_credentials: []  
    
  - name: Recreate credentials on target AAP
    include_tasks: prepare_creds_to_apply.yml
    vars:
      mycred: "{{item}}"
    loop: "{{all_credentials.json.results | map(attribute='id') | list}}"